In [1]:
import random

random_number = random.randint(1, 100)
print(random_number)

50


In [4]:
import random
node_id_list = []
tads_list = []
abcompartment_list = []
for i in range(39):
    node_id_list.append(i)
    tads_list.append(random.randint(1, 20))
    abcompartment_list.append(random.randint(1, 5))
print(node_id_list)
print(tads_list)
print(abcompartment_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]
[12, 16, 11, 6, 9, 11, 17, 8, 2, 19, 20, 13, 6, 15, 13, 12, 3, 5, 19, 4, 7, 8, 1, 20, 20, 19, 18, 10, 13, 4, 2, 9, 6, 19, 7, 13, 14, 5, 10]
[3, 4, 5, 3, 4, 2, 5, 3, 5, 4, 3, 1, 3, 3, 5, 1, 3, 3, 2, 1, 5, 5, 2, 4, 4, 4, 3, 2, 4, 3, 5, 3, 3, 5, 3, 1, 4, 4, 3]


In [5]:
total_list = [x for y in zip(node_id_list, tads_list, abcompartment_list) for x in y]
print(total_list)

[0, 12, 3, 1, 16, 4, 2, 11, 5, 3, 6, 3, 4, 9, 4, 5, 11, 2, 6, 17, 5, 7, 8, 3, 8, 2, 5, 9, 19, 4, 10, 20, 3, 11, 13, 1, 12, 6, 3, 13, 15, 3, 14, 13, 5, 15, 12, 1, 16, 3, 3, 17, 5, 3, 18, 19, 2, 19, 4, 1, 20, 7, 5, 21, 8, 5, 22, 1, 2, 23, 20, 4, 24, 20, 4, 25, 19, 4, 26, 18, 3, 27, 10, 2, 28, 13, 4, 29, 4, 3, 30, 2, 5, 31, 9, 3, 32, 6, 3, 33, 19, 5, 34, 7, 3, 35, 13, 1, 36, 14, 4, 37, 5, 4, 38, 10, 3]


In [6]:
print(len(total_list))

117


In [29]:
# code
import random
import numpy as np

for j in range(1,6):
    final_list = []
    for times in range(300):
        node_id_list = []
        tads_list = []
        abcompartment_list = []
        for i in range(200):
            node_id_list.append(i)
            tads_list.append(random.randint(1, 20))
            abcompartment_list.append(random.randint(1, 5))
        #print(node_id_list)
        #print(tads_list)
        #print(abcompartment_list)
        total_list = [x for y in zip(node_id_list, tads_list, abcompartment_list) for x in y]
        #print(total_list)
        final_list.append(total_list)
        #print("\n")
        final_array = np.array(final_list)

    print(final_array)
    print(len(final_array[0]))
    save_path = "/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/cmu/train/hic/hic_" + str(j) + ".txt"

    f = open(save_path,'a')
    f.close()
    print(save_path)
    np.savetxt(save_path, final_array,fmt='%d',delimiter=',')
    


[[  0  18   3 ... 199  18   3]
 [  0   6   2 ... 199   2   1]
 [  0  19   4 ... 199  14   4]
 ...
 [  0  16   4 ... 199   1   5]
 [  0  20   4 ... 199   6   5]
 [  0  16   3 ... 199  11   4]]
600
/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/cmu/train/hic/hic_1.txt
[[  0  11   2 ... 199   6   1]
 [  0   7   1 ... 199  15   2]
 [  0  15   2 ... 199   1   3]
 ...
 [  0  19   2 ... 199  17   2]
 [  0   5   3 ... 199  17   1]
 [  0   5   5 ... 199  18   5]]
600
/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/cmu/train/hic/hic_2.txt
[[  0   4   2 ... 199   9   4]
 [  0   4   4 ... 199   1   1]
 [  0  18   5 ... 199   8   2]
 ...
 [  0  20   3 ... 199  12   2]
 [  0  20   4 ... 199   8   5]
 [  0   5   2 ... 199  14   3]]
600
/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/cmu/train/hic/hic_3.txt
[[  0   7   3 ... 199   2   2]
 [  0   4   4 ... 199   5   2]
 [  0   2   2 ... 199   1   4]
 ...
 [  0   1   5 ... 199  18   4]
 [  0  13   4 ... 199  18   2]
 [  0 

In [30]:
for j in range(1,2):
    final_list = []
    for times in range(300):
        node_id_list = []
        tads_list = []
        abcompartment_list = []
        for i in range(200):
            node_id_list.append(i)
            tads_list.append(random.randint(1, 20))
            abcompartment_list.append(random.randint(1, 5))
        #print(node_id_list)
        #print(tads_list)
        #print(abcompartment_list)
        total_list = [x for y in zip(node_id_list, tads_list, abcompartment_list) for x in y]
        #print(total_list)
        final_list.append(total_list)
        #print("\n")
        final_array = np.array(final_list)

    print(final_array)
    print(len(final_array[0]))
    save_path = "/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/cmu/test/hic/hic_" + str(j) + ".txt"

    f = open(save_path,'a')
    f.close()
    print(save_path)
    np.savetxt(save_path, final_array,fmt='%d',delimiter=',')

[[  0  18   4 ... 199  16   2]
 [  0  20   1 ... 199  17   3]
 [  0   3   3 ... 199  14   2]
 ...
 [  0   2   1 ... 199  15   3]
 [  0  15   3 ... 199  14   2]
 [  0  13   3 ... 199  19   1]]
600
/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/cmu/test/hic/hic_1.txt


In [29]:
import numpy as np
final_array = np.array(final_list)
print(final_array)
print(len(final_array))

[[ 0 14  3 ... 38  1  4]
 [ 0 13  5 ... 38  8  3]
 [ 0 14  1 ... 38 12  5]
 ...
 [ 0  7  4 ... 38  1  3]
 [ 0 20  4 ... 38 18  5]
 [ 0  3  2 ... 38 13  3]]
300


In [30]:
np.savetxt("/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/cmu/test/walking/walking_1.txt", final_array,fmt='%d',delimiter=',')

In [13]:
import numpy as np
import random
import copy

import os

import hicstraw
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import torch
from torch_geometric.data import Data
import math
from torch_geometric.nn import GCNConv
from sklearn.metrics import roc_auc_score
import torch.nn.functional as F
from scipy.sparse import coo_matrix
from torch_geometric.utils import convert
from torch_geometric.utils import train_test_split_edges
from sklearn.metrics import roc_auc_score
from torch_geometric.utils import negative_sampling
import scipy.sparse as sp

def load_data(cell_id, chrom):
    root = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test" # 文件夹路径，相对路径or绝对路径都可以
    # 获取文件夹所有文件
    files_list = os.listdir(root) # 示例 ["1.txt","2.txt","2.gif","child_folder_name","2.jpg"]

    ## 常见操作
    # 1.获取指定后缀（如txt）的文件
    filter_files_list_10kb = [fn for fn in files_list if fn.endswith("_chrom"+str(chrom)+"_10kb.txt")]
    #print(filter_files_list_10kb)
    cell_id_name = filter_files_list_10kb[cell_id]
    
    file_path_test = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_10kb.txt"
    print(file_path_test)
    data_test = np.loadtxt(file_path_test,dtype=int,delimiter='\t')
    print(data_test)
    col = data_test[:,0]
    row  = data_test[:,1]
    value = data_test[:,2]
    print(col,row,value)

    max_nodes = int(max(max(col),max(row))+1)

    sp_coo_m = sp.coo_matrix((value,(row,col)),shape = (max_nodes,max_nodes))
    #print(sp_coo_m)
    up_delta = sp_coo_m.todense()
    down_delta = up_delta.transpose()
    diag1 = np.diagonal(up_delta)
    diagn = np.diag(diag1)
    complete_matrix = up_delta + down_delta - diagn
    print(complete_matrix)
    #t_complete_matrix = torch.from_numpy(complete_matrix)
    #t_complete_matrix_100kb = t_complete_matrix.unsqueeze(dim=0)
    complete_matrix_10kb_test  = complete_matrix[0:200,0:200]
    np.savetxt("/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/hic_matrix/nodes_200.txt", complete_matrix_10kb_test,fmt='%d',delimiter=',')

    file_path_test = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_50kb.txt"
    print(file_path_test)
    data_test = np.loadtxt(file_path_test,dtype=int,delimiter='\t')
    print(data_test)
    col = data_test[:,0]
    row  = data_test[:,1]
    value = data_test[:,2]
    print(col,row,value)

    max_nodes = int(max(max(col),max(row))+1)

    sp_coo_m = sp.coo_matrix((value,(row,col)),shape = (max_nodes,max_nodes))
    #print(sp_coo_m)
    up_delta = sp_coo_m.todense()
    down_delta = up_delta.transpose()
    diag1 = np.diagonal(up_delta)
    diagn = np.diag(diag1)
    complete_matrix = up_delta + down_delta - diagn
    print(complete_matrix)
    #t_complete_matrix = torch.from_numpy(complete_matrix)
    #t_complete_matrix_100kb = t_complete_matrix.unsqueeze(dim=0)
    complete_matrix_50kb_test  = complete_matrix[0:40,0:40]
    np.savetxt("/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/hic_matrix/nodes_40.txt", complete_matrix_50kb_test,fmt='%d',delimiter=',')

    file_path_test = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_100kb.txt"
    print(file_path_test)
    data_test = np.loadtxt(file_path_test,dtype=int,delimiter='\t')
    print(data_test)
    col = data_test[:,0]
    row  = data_test[:,1]
    value = data_test[:,2]
    print(col,row,value)

    max_nodes = int(max(max(col),max(row))+1)

    sp_coo_m = sp.coo_matrix((value,(row,col)),shape = (max_nodes,max_nodes))
    #print(sp_coo_m)
    up_delta = sp_coo_m.todense()
    down_delta = up_delta.transpose()
    diag1 = np.diagonal(up_delta)
    diagn = np.diag(diag1)
    complete_matrix = up_delta + down_delta - diagn
    print(complete_matrix)
    #t_complete_matrix = torch.from_numpy(complete_matrix)
    #t_complete_matrix_100kb = t_complete_matrix.unsqueeze(dim=0)
    complete_matrix_100kb_test  = complete_matrix[0:20,0:20]
    np.savetxt("/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/hic_matrix/nodes_20.txt", complete_matrix_100kb_test,fmt='%d',delimiter=',')

    '''

    filter_files_list_50kb = [fn for fn in files_list if fn.endswith("_chrom"+str(chrom)+"_50kb.txt")]
    #print(filter_files_list_10kb)
    cell_id_name = filter_files_list_50kb[cell_id]
    
    file_path_test = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/" + str(cell_id_name)
    #print(file_path_test)
    data_test = np.loadtxt(file_path_test,dtype=int,delimiter='\t')
    #print(data_test)
    col = data_test[:,0]
    row  = data_test[:,1]
    value = data_test[:,2]
    #print(col,row,value)

    max_nodes =int (max(col)+1)
    print(max_nodes)
    t_col = torch.from_numpy(col)
    print(t_col)
    t_row = torch.from_numpy(row)
    print(t_row)
    t_value = torch.from_numpy(value)

    sp_coo_m = sp.coo_matrix((t_value,(t_row,t_col)),shape = (max_nodes,max_nodes))
    #print(sp_coo_m)
    up_delta = sp_coo_m.todense()
    down_delta = up_delta.transpose()
    diag1 = np.diagonal(up_delta)
    diagn = np.diag(diag1)
    complete_matrix = up_delta + down_delta - diagn
    #print(complete_matrix)
    t_complete_matrix = torch.from_numpy(complete_matrix)
    t_complete_matrix_50kb = t_complete_matrix.unsqueeze(dim=0)

    filter_files_list_100kb = [fn for fn in files_list if fn.endswith("_chrom"+str(chrom)+"_100kb.txt")]
    #print(filter_files_list_10kb)
    cell_id_name = filter_files_list_100kb[cell_id]
    
    file_path_test = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/" + str(cell_id_name)
    #print(file_path_test)
    data_test = np.loadtxt(file_path_test,dtype=int,delimiter='\t')
    #print(data_test)
    col = data_test[:,0]
    row  = data_test[:,1]
    value = data_test[:,2]
    #print(col,row,value)
    max_nodes = int(max(max(col),max(row))+1)

    sp_coo_m = sp.coo_matrix((value,(row,col)),shape = (max_nodes,max_nodes))
    #print(sp_coo_m)
    up_delta = sp_coo_m.todense()
    down_delta = up_delta.transpose()
    diag1 = np.diagonal(up_delta)
    diagn = np.diag(diag1)
    complete_matrix = up_delta + down_delta - diagn
    #print(complete_matrix)
    #t_complete_matrix = torch.from_numpy(complete_matrix)
    #t_complete_matrix_100kb = t_complete_matrix.unsqueeze(dim=0)
    t_complete_matrix_10kb_test  = complete_matrix[0:26,0:26]
    '''
    return complete_matrix_10kb_test,complete_matrix_50kb_test


x = load_data(0,1)
print(x)

/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_10kb.txt
[[   10     9     1]
 [   18    13     1]
 [   18    18     1]
 ...
 [19226 19063     1]
 [19226 19223     1]
 [19229 19061     1]]
[   10    18    18 ... 19226 19226 19229] [    9    13    18 ... 19063 19223 19061] [1 1 1 ... 1 1 1]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_50kb.txt
[[   2    1    1]
 [   3    2    2]
 [   3    3    3]
 ...
 [3845 2913    1]
 [3845 3812    2]
 [3845 3844    1]]
[   2    3    3 ... 3845 3845 3845] [   1    2    3 ... 2913 3812 3844] [1 2 3 ... 1 2 1]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_100kb.txt


In [46]:
np.savetxt("/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/hic_matrix/nodes_26.txt", x,fmt='%d',delimiter=',')

In [85]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class AveargeJoint(nn.Module):

    def __init__(self):
        super().__init__()
        self.torso = [8,9,10]
        self.left_leg_up = [0,1]
        self.left_leg_down = [2,3]
        self.right_leg_up = [4,5]
        self.right_leg_down = [6,7]
        self.head = [11,12,13]
        self.left_arm_up = [14,15]
        self.left_arm_down = [16,17,18,19]
        self.right_arm_up = [20,21]
        self.right_arm_down = [22,23,24,25]
        
    def forward(self, x):
        x_torso = F.avg_pool2d(x[:, :, self.torso], kernel_size=(1, 3))                                              # [N, C, T, V=1]
        x_leftlegup = F.avg_pool2d(x[:, :, self.left_leg_up], kernel_size=(1, 2))                                # [N, C, T, V=1]
        x_leftlegdown = F.avg_pool2d(x[:, :, self.left_leg_down], kernel_size=(1, 2))                     # [N, C, T, V=1]
        x_rightlegup = F.avg_pool2d(x[:,  :, self.right_leg_up], kernel_size=(1, 2))                        # [N, C, T, V=1]
        x_rightlegdown = F.avg_pool2d(x[ :, :, self.right_leg_down], kernel_size=(1, 2))                   # [N, C, T, V=1]
        x_head = F.avg_pool2d(x[ :, :, self.head], kernel_size=(1, 3))                                              # [N, C, T, V=1]
        x_leftarmup = F.avg_pool2d(x[ :, :, self.left_arm_up], kernel_size=(1, 2))                            # [N, C, T, V=1]
        x_leftarmdown = F.avg_pool2d(x[ :, :, self.left_arm_down], kernel_size=(1, 4))                 # [N, C, T, V=1]
        x_rightarmup = F.avg_pool2d(x[ :, :, self.right_arm_up], kernel_size=(1, 2))                        # [N, C, T, V=1]
        x_rightarmdown = F.avg_pool2d(x[ :, :, self.right_arm_down], kernel_size=(1, 4))               # [N, C, T, V=1]
        x_part = torch.cat((x_leftlegup, x_leftlegdown, x_rightlegup, x_rightlegdown, x_torso, x_head, x_leftarmup, x_leftarmdown, x_rightarmup, x_rightarmdown), dim=-1)               # [N, C, T, V=1]), dim=-1)        # [N, C, T, 10]
        return x_part

In [10]:
x_test = list([[0,20,2,1,17,4,2,20,2,3,7,1,4,2,3,5,3,3,6,18,1,7,10,1,8,15,5,9,5,1,10,2,2,11,11,3,12,16,3,13,4,3,14,6,2,15,8,3,16,19,1,17,3,2,18,6,5,19,5,5,20,4,3,21,4,1,22,20,3,23,19,2,24,19,1,25,2,3,26,1,5,27,9,5,28,16,1,29,14,5,30,7,5,31,2,4,32,10,2,33,19,5,34,1,4,35,5,4,36,11,3,37,11,4,38,10,3],
          [0,14,1,1,11,3,2,13,3,3,15,1,4,11,5,5,5,4,6,7,5,7,6,2,8,12,4,9,17,3,10,11,2,11,16,3,12,9,1,13,19,5,14,20,1,15,13,5,16,7,5,17,1,5,18,9,3,19,20,1,20,1,2,21,11,2,22,1,2,23,5,4,24,3,2,25,13,5,26,1,1,27,19,4,28,11,3,29,12,2,30,9,4,31,6,5,32,6,2,33,5,2,34,2,4,35,1,2,36,5,1,37,5,1,38,14,4]])
x_new1 = x_test[0][0:90]
x_new2 = x_test[1][0:90]
x_new = [x_new1,x_new2]

out_t = torch.tensor(x_new)
print(out_t)
print(out_t.shape)
out_t = out_t.contiguous().view(2,3,30)   
out_t = out_t.permute(0, 1, 2).contiguous()
print(out_t)
print(out_t.shape)


tensor([[ 0, 20,  2,  1, 17,  4,  2, 20,  2,  3,  7,  1,  4,  2,  3,  5,  3,  3,
          6, 18,  1,  7, 10,  1,  8, 15,  5,  9,  5,  1, 10,  2,  2, 11, 11,  3,
         12, 16,  3, 13,  4,  3, 14,  6,  2, 15,  8,  3, 16, 19,  1, 17,  3,  2,
         18,  6,  5, 19,  5,  5, 20,  4,  3, 21,  4,  1, 22, 20,  3, 23, 19,  2,
         24, 19,  1, 25,  2,  3, 26,  1,  5, 27,  9,  5, 28, 16,  1, 29, 14,  5],
        [ 0, 14,  1,  1, 11,  3,  2, 13,  3,  3, 15,  1,  4, 11,  5,  5,  5,  4,
          6,  7,  5,  7,  6,  2,  8, 12,  4,  9, 17,  3, 10, 11,  2, 11, 16,  3,
         12,  9,  1, 13, 19,  5, 14, 20,  1, 15, 13,  5, 16,  7,  5, 17,  1,  5,
         18,  9,  3, 19, 20,  1, 20,  1,  2, 21, 11,  2, 22,  1,  2, 23,  5,  4,
         24,  3,  2, 25, 13,  5, 26,  1,  1, 27, 19,  4, 28, 11,  3, 29, 12,  2]])
torch.Size([2, 90])
tensor([[[ 0, 20,  2,  1, 17,  4,  2, 20,  2,  3,  7,  1,  4,  2,  3,  5,  3,
           3,  6, 18,  1,  7, 10,  1,  8, 15,  5,  9,  5,  1],
         [10,  2,  2, 11, 

In [91]:
s2_init = AveargeJoint()
x_2 = s2_init(out_t)
print(x_2)
print(x_2.shape)

tensor([[[10,  1, 10, 11,  4,  2,  4,  7,  4,  8],
         [ 7,  3,  6,  6,  8, 10,  3,  9,  5, 13],
         [ 2, 12, 12,  5,  9,  8, 21, 11, 21,  7]],

        [[ 7,  1,  7,  7,  7,  5,  5,  5,  6,  7],
         [ 6, 10, 10,  6, 10,  7, 12, 12,  9, 11],
         [ 3, 13, 11, 10,  7, 11, 11,  8, 13, 11]]])
torch.Size([2, 3, 10])


In [99]:
# 修改
import torch
import torch.nn as nn
import torch.nn.functional as F
class AveargeJoint(nn.Module):

    def __init__(self):
        super().__init__()
        '''
        self.torso = [8,9,10]
        self.left_leg_up = [0,1]
        self.left_leg_down = [2,3]
        self.right_leg_up = [4,5]
        self.right_leg_down = [6,7]
        self.head = [11,12,13]
        self.left_arm_up = [14,15]
        self.left_arm_down = [16,17,18,19]
        self.right_arm_up = [20,21]
        self.right_arm_down = [22,23,24,25]
        '''
    def forward(self, x):
        x_part = torch.tensor([])
        for i in range(1,6):
            x_temp1 = F.avg_pool2d(x[:, :, (i*2,i*2+1)], kernel_size=(1, 2))
            x_part = torch.cat((x_part,x_temp1),dim = -1)
            
        return x_part


        '''
        x_torso = F.avg_pool2d(x[:, :, self.torso], kernel_size=(1, 3))                                              # [N, C, T, V=1]
        x_leftlegup = F.avg_pool2d(x[:, :, self.left_leg_up], kernel_size=(1, 2))                                # [N, C, T, V=1]
        x_leftlegdown = F.avg_pool2d(x[:, :, self.left_leg_down], kernel_size=(1, 2))                     # [N, C, T, V=1]
        x_rightlegup = F.avg_pool2d(x[:,  :, self.right_leg_up], kernel_size=(1, 2))                        # [N, C, T, V=1]
        x_rightlegdown = F.avg_pool2d(x[ :, :, self.right_leg_down], kernel_size=(1, 2))                   # [N, C, T, V=1]
        x_head = F.avg_pool2d(x[ :, :, self.head], kernel_size=(1, 3))                                              # [N, C, T, V=1]
        x_leftarmup = F.avg_pool2d(x[ :, :, self.left_arm_up], kernel_size=(1, 2))                            # [N, C, T, V=1]
        x_leftarmdown = F.avg_pool2d(x[ :, :, self.left_arm_down], kernel_size=(1, 4))                 # [N, C, T, V=1]
        x_rightarmup = F.avg_pool2d(x[ :, :, self.right_arm_up], kernel_size=(1, 2))                        # [N, C, T, V=1]
        x_rightarmdown = F.avg_pool2d(x[ :, :, self.right_arm_down], kernel_size=(1, 4))               # [N, C, T, V=1]
        x_part = torch.cat((x_leftlegup, x_leftlegdown, x_rightlegup, x_rightlegdown, x_torso, x_head, x_leftarmup, x_leftarmdown, x_rightarmup, x_rightarmdown), dim=-1)               # [N, C, T, V=1]), dim=-1)        # [N, C, T, 10]
        return x_part
    
        '''

In [100]:
s2_init = AveargeJoint()
x_2 = s2_init(out_t)
print(x_2)
print(x_2.shape)

tensor([[[ 1., 10., 11.,  2.,  4.],
         [ 3.,  6.,  6.,  7., 14.],
         [12., 12.,  5., 12., 12.]],

        [[ 1.,  7.,  7.,  3.,  8.],
         [10., 10.,  6.,  9., 10.],
         [13., 11., 10., 10., 11.]]])
torch.Size([2, 3, 5])


In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class AveargeJoint(nn.Module):

    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        x_part = torch.tensor([])
        for i in range(0,10):
            x_temp1 = F.avg_pool2d(x[:, :, (i*3,i*3+1,i*3+2)], kernel_size=(1, 3))
            x_part = torch.cat((x_part,x_temp1),dim = -1)
            
        return x_part
    
s2_init = AveargeJoint()
x_2 = s2_init(out_t)
print(x_2)
print(x_2.shape)

tensor([[[ 7.,  7.,  8.,  3.,  3.,  3.,  8.,  6.,  9.,  5.],
         [ 4.,  8., 10.,  6.,  7.,  8., 12.,  7.,  9.,  9.],
         [ 9.,  8., 15., 14., 14., 10., 10., 13., 15., 16.]],

        [[ 5.,  5.,  6.,  6.,  6.,  4.,  6.,  5.,  8.,  9.],
         [ 7., 10.,  7., 12., 11., 11.,  9.,  7., 10., 13.],
         [ 7., 11.,  8., 10.,  9., 14.,  9., 16., 14., 14.]]])
torch.Size([2, 3, 10])


In [ ]:
class PartLocalInform(nn.Module):

    def __init__(self):
        super().__init__()

        self.torso = [8,9,10]
        self.left_leg_up = [0,1]
        self.left_leg_down = [2,3]
        self.right_leg_up = [4,5]
        self.right_leg_down = [6,7]
        self.head = [11,12,13]
        self.left_arm_up = [14,15]
        self.left_arm_down = [16,17,18,19]
        self.right_arm_up = [20,21]
        #self.right_arm_down = [22,23,24,25]
        self.right_arm_down = [22,23,24,25,26,27,28,29]

    def forward(self, part):
        N, d, T, w = part.size()  # [64, 256, 7, 10]

        #x = part.new_zeros((N, d, T, 26))
        x = part.new_zeros((N, d, T, 30))

        x[:,:,:,self.left_leg_up] = torch.cat((part[:,:,:,0].unsqueeze(-1), part[:,:,:,0].unsqueeze(-1)),-1)
        x[:,:,:,self.left_leg_down] = torch.cat((part[:,:,:,1].unsqueeze(-1), part[:,:,:,1].unsqueeze(-1)),-1)
        x[:,:,:,self.right_leg_up] = torch.cat((part[:,:,:,2].unsqueeze(-1), part[:,:,:,2].unsqueeze(-1)),-1)
        x[:,:,:,self.right_leg_down] = torch.cat((part[:,:,:,3].unsqueeze(-1), part[:,:,:,3].unsqueeze(-1)),-1)
        x[:,:,:,self.torso] = torch.cat((part[:,:,:,4].unsqueeze(-1), part[:,:,:,4].unsqueeze(-1), part[:,:,:,4].unsqueeze(-1)),-1)
        x[:,:,:,self.head] = torch.cat((part[:,:,:,5].unsqueeze(-1), part[:,:,:,5].unsqueeze(-1), part[:,:,:,5].unsqueeze(-1)),-1)
        x[:,:,:,self.left_arm_up] = torch.cat((part[:,:,:,6].unsqueeze(-1),part[:,:,:,6].unsqueeze(-1)),-1)
        x[:,:,:,self.left_arm_down] = torch.cat((part[:,:,:,7].unsqueeze(-1), part[:,:,:,7].unsqueeze(-1), part[:,:,:,7].unsqueeze(-1), part[:,:,:,7].unsqueeze(-1)),-1)
        x[:,:,:,self.right_arm_up] = torch.cat((part[:,:,:,8].unsqueeze(-1), part[:,:,:,8].unsqueeze(-1)),-1)
        x[:,:,:,self.right_arm_down] = torch.cat((part[:,:,:,9].unsqueeze(-1), part[:,:,:,9].unsqueeze(-1), part[:,:,:,9].unsqueeze(-1), part[:,:,:,9].unsqueeze(-1),part[:,:,:,9].unsqueeze(-1), part[:,:,:,9].unsqueeze(-1), part[:,:,:,9].unsqueeze(-1), part[:,:,:,9].unsqueeze(-1)),-1)

        return x

In [14]:
class PartLocalInform(nn.Module):

    def __init__(self):
        super().__init__()
        '''
        self.torso = [8,9,10]
        self.left_leg_up = [0,1]
        self.left_leg_down = [2,3]
        self.right_leg_up = [4,5]
        self.right_leg_down = [6,7]
        self.head = [11,12,13]
        self.left_arm_up = [14,15]
        self.left_arm_down = [16,17,18,19]
        self.right_arm_up = [20,21]
        #self.right_arm_down = [22,23,24,25]
        self.right_arm_down = [22,23,24,25,26,27,28,29]
        '''

    def forward(self, part):
        N, d, T, w = part.size()  # [64, 256, 7, 10]

        #x = part.new_zeros((N, d, T, 26))
        x = part.new_zeros((N, d, T, 30))

        for i in range(0,10):
            x[:,:,:,(i*3,i*3+1,i*3+2)] = torch.cat((part[:,:,:,i].unsqueeze(-1), part[:,:,:,i].unsqueeze(-1)),part[:,:,:,i].unsqueeze(-1),-1)

        return x

## node_matrix 

In [1]:
import numpy as np
import random
import copy

import os

import hicstraw
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import torch
from torch_geometric.data import Data
import math
from torch_geometric.nn import GCNConv
from sklearn.metrics import roc_auc_score
import torch.nn.functional as F
from scipy.sparse import coo_matrix
from torch_geometric.utils import convert
from torch_geometric.utils import train_test_split_edges
from sklearn.metrics import roc_auc_score
from torch_geometric.utils import negative_sampling
import scipy.sparse as sp

def load_data(cell_id, chrom):
    #root = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test" # 文件夹路径，相对路径or绝对路径都可以
    root = r"/data_disk/data/GSE162511"
    # 获取文件夹所有文件
    files_list = os.listdir(root) # 示例 ["1.txt","2.txt","2.gif","child_folder_name","2.jpg"]

    ## 常见操作
    # 1.获取指定后缀（如txt）的文件
    filter_files_list = [fn for fn in files_list if fn.endswith(".hic")]
    #print(filter_files_list_10kb)
    test = filter_files_list[0:2]
    for i in test:
    
        file_path_test = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/"+str(i)+"_chrom"+str(chrom)+"_10kb.txt"
        print(file_path_test)
        data_test = np.loadtxt(file_path_test,dtype=int,delimiter='\t')
        print(data_test)
        col = data_test[:,0]
        row  = data_test[:,1]
        value = data_test[:,2]
        print(col,row,value)

        max_nodes = int(max(max(col),max(row))+1)

        sp_coo_m = sp.coo_matrix((value,(row,col)),shape = (max_nodes,max_nodes))
        #print(sp_coo_m)
        up_delta = sp_coo_m.todense()
        down_delta = up_delta.transpose()
        diag1 = np.diagonal(up_delta)
        diagn = np.diag(diag1)
        complete_matrix = up_delta + down_delta - diagn
        print(complete_matrix)
        #t_complete_matrix = torch.from_numpy(complete_matrix)
        #t_complete_matrix_100kb = t_complete_matrix.unsqueeze(dim=0)
        complete_matrix_10kb_test  = complete_matrix[0:200,0:200]
        print(complete_matrix_10kb_test)
        print(complete_matrix_10kb_test.shape)
        #np.savetxt("/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/hic_matrix/nodes_200.txt", complete_matrix_10kb_test,fmt='%d',delimiter=',')
    '''
    file_path_test = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_50kb.txt"
    print(file_path_test)
    data_test = np.loadtxt(file_path_test,dtype=int,delimiter='\t')
    print(data_test)
    col = data_test[:,0]
    row  = data_test[:,1]
    value = data_test[:,2]
    print(col,row,value)

    max_nodes = int(max(max(col),max(row))+1)

    sp_coo_m = sp.coo_matrix((value,(row,col)),shape = (max_nodes,max_nodes))
    #print(sp_coo_m)
    up_delta = sp_coo_m.todense()
    down_delta = up_delta.transpose()
    diag1 = np.diagonal(up_delta)
    diagn = np.diag(diag1)
    complete_matrix = up_delta + down_delta - diagn
    print(complete_matrix)
    #t_complete_matrix = torch.from_numpy(complete_matrix)
    #t_complete_matrix_100kb = t_complete_matrix.unsqueeze(dim=0)
    complete_matrix_50kb_test  = complete_matrix[0:40,0:40]
    np.savetxt("/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/hic_matrix/nodes_40.txt", complete_matrix_50kb_test,fmt='%d',delimiter=',')

    file_path_test = r"/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_100kb.txt"
    print(file_path_test)
    data_test = np.loadtxt(file_path_test,dtype=int,delimiter='\t')
    print(data_test)
    col = data_test[:,0]
    row  = data_test[:,1]
    value = data_test[:,2]
    print(col,row,value)

    max_nodes = int(max(max(col),max(row))+1)

    sp_coo_m = sp.coo_matrix((value,(row,col)),shape = (max_nodes,max_nodes))
    #print(sp_coo_m)
    up_delta = sp_coo_m.todense()
    down_delta = up_delta.transpose()
    diag1 = np.diagonal(up_delta)
    diagn = np.diag(diag1)
    complete_matrix = up_delta + down_delta - diagn
    print(complete_matrix)
    #t_complete_matrix = torch.from_numpy(complete_matrix)
    #t_complete_matrix_100kb = t_complete_matrix.unsqueeze(dim=0)
    complete_matrix_100kb_test  = complete_matrix[0:20,0:20]
    np.savetxt("/data_disk/zhangqq/josie-gnn-code/recomb/3-try-dmgnn/data/hic_matrix/nodes_20.txt", complete_matrix_100kb_test,fmt='%d',delimiter=',')
    
    return complete_matrix_10kb_test,complete_matrix_50kb_test
    '''


x = load_data(0,1)
print(x)

/home/zhangqq/anaconda3_new/envs/scgnnEnv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/hippocampus-p056-cb_059.hic_chrom1_10kb.txt
[[   10     9     1]
 [   18    13     1]
 [   18    18     1]
 ...
 [19226 19063     1]
 [19226 19223     1]
 [19229 19061     1]]
[   10    18    18 ... 19226 19226 19229] [    9    13    18 ... 19063 19223 19061] [1 1 1 ... 1 1 1]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(200, 200)
/data_disk/zhangqq/josie-gnn-code/recomb/2-try-dmgnn/data_test/cortex-p007-cb_067.hic_chrom1_10kb.txt
[[   14    10     1]
 [   19    19     1]
 [   20    20     1]
 ...
 [19228 19228     1]
 [19230 19230     1]
 [19236 19233     1]]
[   14    19    20 ... 19228 19230 19236] [   10    19    20 ... 19228 19230 19233] [1 1 1 ... 1 1 1]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ..